### ISSUE TITLE
Mapping DD2 data

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/seedcase-project#11]
- What data do they have
- Where are they each located at (server location, institution responsible, etc)
- Who owns what data

Action items:

- [ ] Alisa to write the first version of the interview guide
- [ ] Annelli to present the idea to DD2 **Wednesday Mar 30th**

Misc items to do:

- (Luke & Alisa) Contact others (F, S, S, T) for a meeting to involve them in project for mapping DD2 (first get confirmation for collaborating with them)

**Comment by AlisaDK** [comment]
F-Frederik, S- Sia, S-Sidsel, T-Torben Hansen
