### ISSUE TITLE
Reasons for why we choose containers over other installation format

### ISSUE THREAD

**Issue by lwjohnst86** [steno-aarhus/seedcase-project#44]
Write content as markdown in the [`design/decisions/why-container/index.md`](https://github.com/steno-aarhus/seedcase-project/blob/main/design/decisions/why-container/index.md) file.

**Comment by rqding** [comment]
I think this task could be combined with Issue #39. In the output document of issue 39 it should provide a suggestion and reason for the suggestion.

**Comment by rqding** [comment]
Add the first draft. Please review it when you have time.
