### ISSUE TITLE
Create System Design Document

### ISSUE THREAD

**Issue by rqding** [steno-aarhus/seedcase-project#50]
The system design document helps to ensure that the system will meet the needs of the organization or user: By creating a system design, it is possible to identify and plan for the specific needs and requirements of the organization or user. This can help to ensure that the final system will be well-suited to the organization's goals and objectives, and will be able to support the organization's operations and processes. The system design provides a clear and comprehensive plan for implementation: A system design serves as a roadmap for the development and implementation of the system. The system design also helps to identify potential problems and issues: By creating a system design, it is possible to identify potential problems or issues that may arise during the development and implementation of the system.

**Comment by lwjohnst86** [comment]
This is kinda covered by #72 and #78. So closing for now.
