### ISSUE TITLE
Complete `design/architecture/api.md` with detailed description of the API endpoints for upload data and download data

### ISSUE THREAD

**Issue by rqding** [steno-aarhus/seedcase-project#56]
Inside this document will be a very practical, detailed description of what the API will actually look like. The most explicitly described, the easier it is for use Meaning, what are the endpoints, and what are the `GET` or `PUT` requests. For instance, when people input data, what is the `PUT` endpoint look like? When people browse the list of variables in the database, what are the `GET` requests to build the listing of variables? This document isn't the ground truth, it's a starting point for us to have a tangible thing to talk about and work on and get reviewed. Please use the document to add your own thoughts and brainstormed ideas! We can always trim it later.

**Comment by lwjohnst86** [comment]
Expand on security in  [`design/security.md`](https://github.com/steno-aarhus/seedcase-project/blob/main/design/security.md). See also #57.

**Comment by lwjohnst86** [comment]
This issue is basically covered by other issues
